name: uni_overlay_log_example
description: Exemplo oficial do pacote uni_overlay_log
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  uni_overlay_log:
    path: ../

flutter:
  uses-material-design: true