include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    unnecessary_this: true
    always_declare_return_types: true
    omit_local_variable_types: false